server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Проксирование запросов к API, если не хочешь писать полный URL в коде
    # Но пока оставим просто статику, так как у тебя CORS на бэкенде разрешен
}
